"""Pydantic schemas for question generation endpoints."""

from datetime import datetime

from pydantic import BaseModel, Field

from app.config import settings


class QuestionGenerationRequest(BaseModel):
    """Request model for question generation."""

    num_questions: int = Field(
        default=settings.default_questions_per_document,
        ge=1,
        le=settings.max_questions_per_request,
        description="Number of questions to generate and store",
    )


class QuestionResponse(BaseModel):
    """Response model for a generated question."""

    id: int = Field(..., description="Question ID")
    document_id: int = Field(..., description="Associated document ID")
    content: str = Field(..., description="Generated question text")
    expected_answer: str | None = Field(
        None, description="Expected answer generated by the LLM"
    )
    created_at: datetime = Field(..., description="Generation timestamp")

    model_config = {"from_attributes": True}


class QuestionGenerationResponse(BaseModel):
    """Response model for generated document questions."""

    document_id: int = Field(..., description="Document that was used for generation")
    requested_count: int = Field(..., description="Requested question count")
    generated_count: int = Field(..., description="Persisted unique question count")
    questions: list[QuestionResponse] = Field(
        default_factory=list,
        description="Generated questions",
    )
