"""add is_embedded to chunks

Revision ID: 60ffda06b9c9
Revises: 946984c9442b
Create Date: 2026-02-11 21:33:53.387296

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "60ffda06b9c9"
down_revision: str | Sequence[str] | None = "946984c9442b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chunks",
        sa.Column(
            "is_embedded", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chunks", "is_embedded")
    # ### end Alembic commands ###
