"""update_embedding_dimension_768

Revision ID: 946984c9442b
Revises: bcfe046193cc
Create Date: 2026-02-11 20:44:57.851349

"""

from collections.abc import Sequence

from alembic import op
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = "946984c9442b"
down_revision: str | Sequence[str] | None = "bcfe046193cc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "chunks",
        "embedding",
        existing_type=Vector(dim=1536),
        type_=Vector(dim=768),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "chunks",
        "embedding",
        existing_type=Vector(dim=768),
        type_=Vector(dim=1536),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
